{{/* some vars to make life easier */}}
{{- $chartName := .Chart.Name }}
{{- $chartVersion := .Chart.Version | replace "+" "_" }}
{{- $chartFullName := printf "%s-%s" $chartName $chartVersion | replace "+" "_" }}
{{- $releaseName := .Release.Name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index .Values "puma" "bc-rates-only" "name" }}
  labels:
    app.kubernetes.io/component: bc-rates-only-frontend
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    helm.sh/chart: {{ $chartFullName }}
spec:
  replicas: {{ index .Values "puma" "bc-rates-only" "replicaCount" }}
  selector:
    matchLabels:
      app.kubernetes.io/component: bc-rates-only-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: bc-rates-only-frontend
        app.kubernetes.io/instance: {{ $releaseName }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ .Values.appName }}
        helm.sh/chart: {{ $chartFullName }}
    spec:
      containers:
      - name: {{ index .Values "puma" "bc-rates-only" "name" }}
        image: "{{ .Values.imageRepo }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.containerPort1 }}
          initialDelaySeconds: 120
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.containerPort1 }}
          initialDelaySeconds: 120
          timeoutSeconds: 3
        tty: true
        stdin: true
        command: ["/bin/sh", "-c"]
        args:
          - |
            {{ index .Values "puma" "bc-rates-only" "command" }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configMapName }}
        # env:
        # - name: RAILS_ENV
        #   value: development
        # - name: RACK_ENV
        #   value: production
        resources:
          requests:
            memory: {{ index .Values "puma" "bc-rates-only" "memoryRequest" | quote }}
            cpu: {{ index .Values "puma" "bc-rates-only" "cpuRequest" | quote }}
          limits:
            memory: {{ index .Values "puma" "bc-rates-only" "memoryLimit" | quote }}
            cpu: {{ index .Values "puma" "bc-rates-only" "cpuLimit" | quote }}
        ports:
          - name: port1
            containerPort: {{ default 3000 .Values.containerPort1 }}
            protocol: TCP

