{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version | replace "+" "_" -}}
{{- $chartFullName := printf "%s-%s" $chartName $chartVersion | replace "+" "_" -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceFullName := printf "%s-%s" .Values.serviceName .Release.Name -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceFullName }}
  labels:
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    helm.sh/chart: {{ $chartFullName }}
spec:
  type: {{ default "ClusterIP" .Values.serviceType }}
  ports:
  - port: {{ .Values.containerPort1 | default 3000 }}
    targetPort: {{ .Values.containerPort1 | default 3000 }}
    protocol: TCP
    name: port1
  selector:
    app.kubernetes.io/component: bc-rates-only-frontend
---
{{- with .Values.nginxIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .name }}-{{ $releaseName }}"
  namespace: {{ .namespace | default "default" }}
  annotations: 
      kubernetes.io/ingress.class: nginx  
spec:
  rules:
  {{- /* Range over all rules in values */ -}}
  {{- range .rules }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: {{ $serviceFullName }}
          servicePort: {{ .servicePort | default 3000 }}
        path: {{ .path }}
  {{- end }}
  {{- if .tls }}
  tls:
  - hosts:
  {{- range .tls.hosts }}
    - {{ . | quote }}
  {{- end }}
    secretName: {{ .tls.secretName }}
  {{- end }}
{{- end }}
