appName: bc-rates-only

imageRepo: gcr.io/copper-mender-240813/bc-rates-only
imageTag: cache-latest
imagePullPolicy: Always

configMapName: bc-rates-only-env

containerPort1: 3000
containerPort2: 8080

serviceName: bc-rates-only-nodeport
serviceType: ClusterIP

puma:
  bc-rates-only:
    name: bc-rates-only
    command: bundle exec puma -C config/puma.rb -b 'tcp://0.0.0.0:3000'
    replicaCount: 1
    memoryRequest: 256Mi
    memoryLimit: 1024Mi
    cpuRequest: 50m
    cpuLimit: 150m

bc-rates-only_tmp_dir: /home/app
bc-rates-only_log_dir: /home/app/log/production.log

# workers:
#   - name: sidekiq
#     command: bundle exec sidekiq -C config/sidekiq.yml
#     memoryRequest: 200Mi
#     memoryLimit: 1200Mi
#     cpuRequest: 50m
#     cpuLimit: 150m

# Values to configure endpoint for nginx-ingress
